name: Test the front ent application application

on:
  push:
    branches: [main]

  pull_request:
    branches: [develop, main]
    types: [assigned, opened, synchronize]

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'front'
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Save node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm --prefix front/ ci

  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
          cache: 'npm'

      - name: Restore node modules from cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run tests
        run: npm --prefix front/ run test
